### ISSUE TITLE
Scala.js source maps point to wrong root

### ISSUE THREAD

**Issue by chuwy** [cquiroz/scala-java-time#25] opened 2017-02-28 11:25 UTC
JS Source maps for `threetenbp` and `scalajs-locales` point to wrong local root `/Users/cquiroz/Projects`. I think this should point to raw.githubusercontent.com similar to cats: https://github.com/typelevel/cats/pull/916

**Comment by cquiroz** [comment] 2017-02-28 12:24
Hi, that's good to know. Thanks for the info

**Comment by cquiroz** [comment] 2017-03-01 19:47
I'm replicating the fix but I'm not sure how to test it, can you comment?

**Comment by cquiroz** [comment] 2017-03-01 23:41
The last PR wasn't correct, reopening

**Comment by chuwy** [comment] 2017-03-06 07:18
Sorry @cquiroz, didn't see your comments.

What exactly went wrong with that PR? 
As for testing, it should emit source maps with line similar to `https://raw.githubusercontent.com/scala-js/scala-js/v0.6.14/tools/scalajsenv.js` as opposed to `file:///Users/cquiroz/Projects/threetenbp/js/target/scala-2.12/src_managed/main/org/threeten/bp/LocalDate.scala`. Here's [example project](https://github.com/metado/toodo) using this library with Scala.js.

**Comment by cquiroz** [comment] 2017-03-06 12:19
The issue is that the default setting works for code in the usual places, but `scala-java-time` has generated code. I think it shouldn't be that hard to get it right

I wonder if you can pass multiple mappings

**Comment by cquiroz** [comment] 2017-03-09 01:01
Fixed by PR #32

**Closed** 2017-03-09 01:02 UTC
